### ISSUE TITLE
npm run-script start ends with exit status 126 #2

### ISSUE THREAD

**Issue by vo-manadev** [tonyhb/redux-boilerplate#5]
Contents of npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'run-script',
1 verbose cli 'start' ]
2 info using npm@3.6.0
3 info using node@v5.7.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle redux-boilerplate@0.0.0~prestart: redux-boilerplate@0.0.0
6 silly lifecycle redux-boilerplate@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle redux-boilerplate@0.0.0~start: redux-boilerplate@0.0.0
8 verbose lifecycle redux-boilerplate@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle redux-boilerplate@0.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;c:_projects\php55\redux-boilerplate\node_modules.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Hewlett-Packard\SimplePass\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\bin;c:\wamp\bin\php\php5.5.12;C:\ProgramData\ComposerSetup\bin;c:_projects\other\bin;c:\wamp\bin\mysql\mysql5.6.17\bin;c:\Program Files\7-Zip;c:\Users\Vladislav\AppData\Roaming\Composer\vendor\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Vagrant\bin;C:\Program Files\nodejs\;c:\Program Files\Intel\WiFi\bin\;c:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\Vladislav\AppData\Roaming\npm
10 verbose lifecycle redux-boilerplate@0.0.0~start: CWD: c:_projects\php55\redux-boilerplate
11 silly lifecycle redux-boilerplate@0.0.0~start: Args: [ '/d /s /c', 'ENV=development node dev.server.js' ]
12 silly lifecycle redux-boilerplate@0.0.0~start: Returned: code: 126 signal: null
13 info lifecycle redux-boilerplate@0.0.0~start: Failed to exec start script
14 verbose stack Error: redux-boilerplate@0.0.0 start: ENV=development node dev.server.js
14 verbose stack Exit status 126
14 verbose stack at EventEmitter. (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack at emitTwo (events.js:100:13)
14 verbose stack at EventEmitter.emit (events.js:185:7)
14 verbose stack at ChildProcess. (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack at emitTwo (events.js:100:13)
14 verbose stack at ChildProcess.emit (events.js:185:7)
14 verbose stack at maybeClose (internal/child_process.js:827:16)
14 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid redux-boilerplate@0.0.0
16 verbose cwd c:_projects\php55\redux-boilerplate
17 error Windows_NT 10.0.10586
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run-script" "start"
19 error node v5.7.1
20 error npm v3.6.0
21 error code ELIFECYCLE
22 error redux-boilerplate@0.0.0 start: ENV=development node dev.server.js
22 error Exit status 126
23 error Failed at the redux-boilerplate@0.0.0 start script 'ENV=development node dev.server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the redux-boilerplate package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error ENV=development node dev.server.js
23 error You can get information on how to open an issue for this project with:
23 error npm bugs redux-boilerplate
23 error Or if that isn't available, you can get their info via:
23 error npm owner ls redux-boilerplate
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by devnegikec** [comment]
I had similar issue, removed ENV=development from start script 

{
....
"start": "node dev.server.js",
....
}
run command 

> npm run start
